import type { ReportTriggeredBy } from '@/types/report';

/** Human label for a report type token. */
export function reportTypeLabel(type: string): string {
  switch (type) {
    case 'ad_hoc':
      return 'Ad Hoc';
    case 'scheduled':
      return 'Scheduled';
    default:
      return type;
  }
}

/** Format a report's generation timestamp for a metadata byline. */
export function formatReportDateTime(iso: string): string {
  return new Date(iso).toLocaleString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  });
}

/** Byline fragment for who triggered the report, or empty string if unknown. */
export function triggeredByLabel(triggeredBy: ReportTriggeredBy | null): string {
  return triggeredBy ? `Generated by ${triggeredBy.displayName}` : '';
}
