import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { render, screen, cleanup, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router'
import ReportsPage from '@/pages/reports'
import { useReports, invalidateReports } from '@/hooks/use-reports'
import { apiPost } from '@/lib/api'
import type { ReportSummary } from '@/types/report'

const navigateMock = vi.fn()
vi.mock('react-router', async (importOriginal) => ({
  ...(await importOriginal<typeof import('react-router')>()),
  useNavigate: () => navigateMock,
}))
vi.mock('@/hooks/use-reports', () => ({
  useReports: vi.fn(),
  invalidateReports: vi.fn(() => Promise.resolve()),
}))
vi.mock('@/lib/api', () => ({ apiPost: vi.fn(), getErrorMessage: (e: unknown) => String(e) }))
vi.mock('sonner', () => ({ toast: { success: vi.fn(), error: vi.fn() } }))

const mockedUseReports = useReports as ReturnType<typeof vi.fn>
const mockedApiPost = apiPost as ReturnType<typeof vi.fn>

const newer: ReportSummary = { id: 'r2', generatedAt: '2026-06-10T12:00:00+00:00', type: 'ad_hoc', triggeredBy: { id: 'u1', displayName: 'Ada' } }
const older: ReportSummary = { id: 'r1', generatedAt: '2026-06-01T09:00:00+00:00', type: 'scheduled', triggeredBy: null }

function hookState(over: Partial<ReturnType<typeof useReports>>) {
  return { data: undefined, isPending: false, isError: false, refetch: vi.fn(), ...over } as ReturnType<typeof useReports>
}

function renderPage() {
  return render(<MemoryRouter><ReportsPage /></MemoryRouter>)
}

describe('ReportsPage — archive', () => {
  beforeEach(() => {
    navigateMock.mockReset()
    mockedUseReports.mockReset()
    mockedApiPost.mockReset()
    ;(invalidateReports as ReturnType<typeof vi.fn>).mockClear()
  })
  afterEach(cleanup)

  it('renders rows in the given (newest-first) order with date, type badge, and byline', () => {
    mockedUseReports.mockReturnValue(hookState({ data: [newer, older] }))
    renderPage()

    expect(screen.getByText('Ad Hoc')).toBeInTheDocument()
    expect(screen.getByText('Scheduled')).toBeInTheDocument()
    expect(screen.getByText(/Generated by Ada/)).toBeInTheDocument()

    const links = screen.getAllByRole('link')
    expect(links[0]).toHaveAttribute('href', '/reports/r2') // newer first
    expect(links[1]).toHaveAttribute('href', '/reports/r1')
  })

  it('shows a loading state while pending', () => {
    mockedUseReports.mockReturnValue(hookState({ isPending: true }))
    renderPage()
    expect(screen.getByRole('status')).toBeInTheDocument()
  })

  it('shows an empty state when there are no reports', () => {
    mockedUseReports.mockReturnValue(hookState({ data: [] }))
    renderPage()
    expect(screen.getByText(/generate your first/i)).toBeInTheDocument()
  })

  it('shows an error state on failure', () => {
    mockedUseReports.mockReturnValue(hookState({ isError: true }))
    renderPage()
    expect(screen.getByText(/failed to load/i)).toBeInTheDocument()
  })
})

describe('ReportsPage — generate', () => {
  beforeEach(() => {
    navigateMock.mockReset()
    mockedUseReports.mockReturnValue(hookState({ data: [] }))
    mockedApiPost.mockReset()
    ;(invalidateReports as ReturnType<typeof vi.fn>).mockClear()
  })
  afterEach(cleanup)

  it('generates a report, invalidates the archive, and navigates to the new detail view', async () => {
    const user = userEvent.setup()
    mockedApiPost.mockResolvedValue({ report: { id: 'rNew' } })
    renderPage()

    await user.click(screen.getByRole('button', { name: /generate report/i }))

    await waitFor(() => expect(mockedApiPost).toHaveBeenCalledWith('/reports'))
    expect(invalidateReports).toHaveBeenCalled()
    expect(navigateMock).toHaveBeenCalledWith('/reports/rNew')
  })
})
