import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { render, screen, cleanup } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter, Routes, Route } from 'react-router'
import ReportDetailPage from '@/pages/report-detail'
import { useReport } from '@/hooks/use-reports'
import { downloadReportMarkdown } from '@/lib/download'
import type { ReportDetail } from '@/types/report'

vi.mock('@/hooks/use-reports', () => ({ useReport: vi.fn() }))
vi.mock('@/lib/download', () => ({ downloadReportMarkdown: vi.fn(() => Promise.resolve()) }))
vi.mock('sonner', () => ({ toast: { success: vi.fn(), error: vi.fn() } }))

const mockedUseReport = useReport as ReturnType<typeof vi.fn>
const mockedDownload = downloadReportMarkdown as ReturnType<typeof vi.fn>

const detail: ReportDetail = {
  id: 'r1',
  generatedAt: '2026-06-10T12:00:00+00:00',
  type: 'ad_hoc',
  triggeredBy: { id: 'u1', displayName: 'Ada' },
  windowDays: 14,
  payload: {
    generatedAt: '2026-06-10T12:00:00+00:00',
    windowDays: 14,
    milestoneHorizonDays: 90,
    milestones: [],
    projects: [],
    projectsEmpty: true,
    copy: { noProjects: 'No projects.', noActiveTasks: 'None.', noMilestones: 'No milestones.', unassigned: 'Unassigned' },
  },
}

function renderAt(id = 'r1') {
  return render(
    <MemoryRouter initialEntries={[`/reports/${id}`]}>
      <Routes>
        <Route path="/reports/:id" element={<ReportDetailPage />} />
        <Route path="/reports" element={<div>archive</div>} />
      </Routes>
    </MemoryRouter>,
  )
}

function hookState(over: Partial<ReturnType<typeof useReport>>) {
  return { data: undefined, isPending: false, isError: false, refetch: vi.fn(), ...over } as ReturnType<typeof useReport>
}

describe('ReportDetailPage', () => {
  beforeEach(() => {
    mockedUseReport.mockReset()
    mockedDownload.mockReset().mockResolvedValue(undefined)
  })
  afterEach(cleanup)

  it('renders the report metadata byline and the blind-rendered payload', () => {
    mockedUseReport.mockReturnValue(hookState({ data: detail }))
    renderAt()

    expect(screen.getByText(/Generated by Ada/)).toBeInTheDocument()
    expect(screen.getByText('Ad Hoc')).toBeInTheDocument()
    // ReportView is mounted (milestone heading present).
    expect(screen.getByRole('heading', { name: /Milestones \(next 90 days\)/ })).toBeInTheDocument()
  })

  it('has a back link to the archive', () => {
    mockedUseReport.mockReturnValue(hookState({ data: detail }))
    renderAt()

    expect(screen.getByRole('link', { name: /back/i })).toHaveAttribute('href', '/reports')
  })

  it('downloads markdown for the current report id', async () => {
    const user = userEvent.setup()
    mockedUseReport.mockReturnValue(hookState({ data: detail }))
    renderAt()

    await user.click(screen.getByRole('button', { name: /download markdown/i }))
    expect(mockedDownload).toHaveBeenCalledWith('r1')
  })

  it('shows a loading state while the query is pending', () => {
    mockedUseReport.mockReturnValue(hookState({ isPending: true }))
    renderAt()

    expect(screen.getByRole('status')).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: /download markdown/i })).not.toBeInTheDocument()
  })

  it('shows an error state on failure', () => {
    mockedUseReport.mockReturnValue(hookState({ isError: true }))
    renderAt()

    expect(screen.getByText(/failed to load/i)).toBeInTheDocument()
  })
})
